name: commitlint
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js